### ISSUE TITLE
obsolete guava dependency blows up clj/cljs compilations

### ISSUE THREAD

**Issue by paultopia** [clojurewerkz/support#4]
Hi there, 

It looks like the guava dependency in here is creating a deeply buried dependency conflict with the closure compiler when one compiles cljs and clj in the same project. 

This turned up for me when I tried to compile a web project using monger on the clj backend, which depends on this library, and also using cljs.  It threw a very obscure error on compiling the cljs. In relevant part: 

> Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.CharMatcher.javaUpperCase()Lcom/google/common/base/CharMatcher;, compiling:(/private/var/folders/y7/2chz_r6x6kl60752vfv7y_tr0000gn/T/form-init1788378285112665096.clj:1:125)

After poking around and doing some heavy google-fu which turned up [this old discussion](https://clojurians-log.clojureverse.org/clojurescript/2016-06-26.html), turns out the problem goes back to guava, and I fixed it by excluding guava from the monger dependency and requiring guava 21.0 myself. 

If upgrading to 21.0 doesn't blow anything up, can I suggest that?

**Comment by michaelklishin** [comment]
Feel free to submit a PR.

**Comment by paultopia** [comment]
Will do. Easiest PR evar :-) 

---
Paul Gowder 
http://paul-gowder.com

My book: The Rule of Law in the Real World
http://rulelaw.net
